config/routes.rb
Rails.application.routes.draw do

    root 'welcome#parallax'
    get '/parallax', to: 'welcome#parallax'
    resources :documents
    resources :users

    get '/signin', to: 'sessions#new'
    post '/signin', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :documents, dependent: :destroy

  validates_uniqueness_of :email
  validates_presence_of :email, :password, :name

  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>'}, default_url: '/images/:style/missing.png',
                    :storage => :s3,
                    :s3_credentials => {
                        :bucket => ENV['S3_BUCKET_NAME'],
                        :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
                        :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'],
                        path: ':class/:attachment/:id/:filename'}
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
    @user = User.new
    @document = Document.new


  end

  def new
    @user = User.new
    respond_to do |f|
      f.html
      f.js
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
          session[:user_id] = @user.id
          redirect_to users_path
          flash[:notice] = 'Thanks For Signing Up!'
    else
      if @user.errors.any?
        flash[:alert] = @user.errors.full_messages
      end
          # flash[:alert] = "Whoops That Didn't Work!"
          redirect_to root_path
    end
  end

  def show

  if User.exists?(params[:id])
    @user = User.find(params[:id])
    p get_id = User.find(params[:id])
    p check_library = get_id[:id]
   if params[:id] != "#{current_user.id}"
     redirect_to current_user
   end
  else
    redirect_to current_user
  end

  end

  def update

    respond_to do |format|
      format.html { if @user.update(user_params)
                      flash[:notice]= 'Update Successful!'
                      redirect_to @user
                    else
                      flash[:notice]= "Looks like you don't have permission to do that!"
                    end
                  }
      format.js
    end

    # if current_user.id == params[:id]
    #
    # else
    #   flash[:notice]= "Whoops! You are unable to edit that user!"
    #   render :show
    # end

  end

  def destroy
    current_user.destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def current_user
    session[:user_id] ? User.find(session[:user_id]) :nil
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :avatar)
  end

  def set_user
    @user = User.find(params[:id])

  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<div class="container-fluid user-index-page">
  <div class="row">
    <div class="col-sm-12 col-sm-3 col-md-3 user_info">
        <div class="row">
          <div class="col-xs-12 col-sm-2 col-md-12">
            <h2><%= "Welcome #{current_user.name}!" %></h2>
            <%= image_tag current_user.avatar.url(:medium), class:'img-responsive img-center' %>
            <br/>

            <br/>
            <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#myModal">
              <%= link_to 'View Commands', '#'%>
            </button>
            <%= link_to 'Upload File', '#', class: 'after_view_command' %>
          </div>
        </div>

    </div>



    <div class="col-xs-12 col-sm-6 col-md-6 user_upload">
      <div class="hide_upload">



      <p><%= render 'shared/new_document_form' %></p>

      <div class="row">
        <div class="col-md-12">
          <h3>Upload Restrictions</h3>
          <ul class="list-group">
            <li class="list-group-item">File must be in PDF format</li>
            <li class="list-group-item">File must not exceed 150MB</li>
            <li class="list-group-item">You must enter a title name</li>
            <li class="list-group-item">At this time only 1 file upload at a time</li>
          </ul>
        </div>
      </div>
      </div>
    </div>

    <div class="clearfix visible-xs-block visible-sm-block"></div>

    <div class="col-xs-12 col-sm-6 col-md-3">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 ">
          <h3>Last 6 Uploads</h3>
          <div class="row">
          <% current_user.documents.last(6).reverse.each do |file| %>

                <div class="col-xs-6 col-md-12 col-sm-12 col-lg-6 user-recent">
                  <div class="image-container image-container-num1">
                    <div class="image image-num1">
                      <%= link_to image_tag(file.pdf(:cover)), document_path(file.id) %>
                    </div>
                    <div class="caption caption-num1">
                      <span class="bottom"><%= link_to file.title, document_path(file.id)%></span>
                    </div>
                  </div>



                </div>

          <% end %>
          </div>
        </div>
      </div>
    </div>



    </div>
    <div class="row">
      <div class="col-md-12 how_to">
        <h3>Commands You Can Use In The PDF Viewer!</h3>

        <div class="row">
          <div class="col-md-4">
            <h4 class="list-group-item-heading">To go to the next page you can say:</h4>
            <ul class="list-group">
              <li class="list-group-item">"Next Page"</li>
              <li class="list-group-item">"Next"</li>
              <li class="list-group-item">"Next Slide"</li>
              <li class="list-group-item">"Forward"</li>
            </ul>
          </div>

          <div class="col-md-4">
            <h4 class="list-group-item-heading">To go to the previous page you can say:</h4>
            <ul class="list-group">
              <li class="list-group-item">"Previous"</li>
              <li class="list-group-item">"Previous Page"</li>
              <li class="list-group-item">"Back"</li>
            </ul>
          </div>

          <div class="col-md-4">
            <h4 class="list-group-item-heading">Why not zoom in? You can say:</h4>
            <ul class="list-group">
              <li class="list-group-item">"Zoom"</li>
              <li class="list-group-item">"Zoom In"</li>
              <li class="list-group-item">"Zoom Closer"</li>
              <li class="list-group-item">"Closer"</li>
              <li class="list-group-item">"Move In"</li>
              <li class="list-group-item">"Move Closer"</li>
            </ul>
          </div>

        </div>

        <div class="row">
          <div class="col-md-6">
            <h4 class="list-group-item-heading">Want to zoom out? Say:</h4>
            <ul class="list-group">
              <li class="list-group-item">"Zoom out"</li>
              <li class="list-group-item">"Zoom Away"</li>
              <li class="list-group-item">"Zoom Fit"</li>
              <li class="list-group-item">"Fit Page"</li>
              <li class="list-group-item">"Fit Screen"</li>
              <li class="list-group-item">"Show All"</li>
            </ul>
          </div>

          <div class="col-md-6">
            <h4 class="list-group-item-heading">Want to change the layout? Say:</h4>
            <ul class="list-group">
              <li class="list-group-item">"Single Page"</li>
              <li class="list-group-item">"Single Page Layout"</li>
              <li class="list-group-item">"Single Page Zoom"</li>
              <li class="list-group-item">"Show One Page"</li>
              <li class="list-group-item">"Show Only One Page"</li>
              <li class="list-group-item">"Show Two Page(s)"</li>
              <li class="list-group-item">"Show Two Page(s) Layout"</li>
              <li class="list-group-item">"Two Page(s) View"</li>
              <li class="list-group-item">"Two Page(s) Layout"</li>
              <li class="list-group-item">"Two Page(s)"</li>
            </ul>
          </div>

        </div>



        <br/>

        <br/>

        <br/>

        <br/>

      </div>

    </div>

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h3 class="modal-title" id="myModalLabel">Commands You Can Use When Viewing Your PDF!</h3>
        </div>
        <div class="modal-body">
              <div class="row">
                <div class="col-md-4">
                  <h4 class="list-group-item-heading">To go to the next page you can say:</h4>
                  <ul class="list-group">
                    <li class="list-group-item">"Next Page"</li>
                    <li class="list-group-item">"Next"</li>
                    <li class="list-group-item">"Next Slide"</li>
                    <li class="list-group-item">"Forward"</li>
                  </ul>
                </div>

                <div class="col-md-4">
                  <h4 class="list-group-item-heading">To go to the previous page you can say:</h4>
                  <ul class="list-group">
                    <li class="list-group-item">"Previous"</li>
                    <li class="list-group-item">"Previous Page"</li>
                    <li class="list-group-item">"Back"</li>
                  </ul>
                </div>

                <div class="col-md-4">
                  <h4 class="list-group-item-heading">Why not zoom in? You can say:</h4>
                  <ul class="list-group">
                    <li class="list-group-item">"Zoom"</li>
                    <li class="list-group-item">"Zoom In"</li>
                    <li class="list-group-item">"Zoom Closer"</li>
                    <li class="list-group-item">"Closer"</li>
                    <li class="list-group-item">"Move In"</li>
                    <li class="list-group-item">"Move Closer"</li>
                  </ul>
                </div>

              </div>

              <div class="row">
                <div class="col-md-6">
                  <h4 class="list-group-item-heading">Want to zoom out? Say:</h4>
                  <ul class="list-group">
                    <li class="list-group-item">"Zoom out"</li>
                    <li class="list-group-item">"Zoom Away"</li>
                    <li class="list-group-item">"Zoom Fit"</li>
                    <li class="list-group-item">"Fit Page"</li>
                    <li class="list-group-item">"Fit Screen"</li>
                    <li class="list-group-item">"Show All"</li>
                  </ul>
                </div>

                <div class="col-md-6">
                  <h4 class="list-group-item-heading">Want to change the layout? Say:</h4>
                  <ul class="list-group">
                    <li class="list-group-item">"Single Page"</li>
                    <li class="list-group-item">"Single Page Layout"</li>
                    <li class="list-group-item">"Single Page Zoom"</li>
                    <li class="list-group-item">"Show One Page"</li>
                    <li class="list-group-item">"Show Only One Page"</li>
                    <li class="list-group-item">"Show Two Page(s)"</li>
                    <li class="list-group-item">"Show Two Page(s) Layout"</li>
                    <li class="list-group-item">"Two Page(s) View"</li>
                    <li class="list-group-item">"Two Page(s) Layout"</li>
                    <li class="list-group-item">"Two Page(s)"</li>
                  </ul>
                </div>

              </div>
        </div>
      </div>
    </div>
  </div>

  </div>

app/views/users/new.html.erb
<h1>NEW</h1>

app/views/users/new.js.erb
$('.fade_login').fadeOut("slow", function(){
    var signin = $( "<div class='fade_login'><%= j render 'shared/new_user_form' %></div>").hide();
    $(this).replaceWith(signin);
    $('.fade_login').fadeIn('slow');
});

app/views/users/show.html.erb
<div class="container-fluid user-show">
  <div class="row">
    <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2">
      <div class="row">
        <div class="col-xs-12 col-md-12 col-lg-12 user-info">
          <h1><%= "#{current_user.name}" %></h1>
          <div class="user_info">
            <%= image_tag(current_user.avatar.url(:thumb)) %>
            <br/>
            <br/>
            <%= link_to 'Update Info', user_path(current_user), method: :put, remote: true, class:'btn btn-primary btn-sm' %>



          </div>
        </div>
      <div class="row">
        <div class="col-xs-12 col-md-12">
          <div class="user_edit">

            <%= render 'shared/edit_user_form' %>

          </div>
        </div>
      </div>
      <!--<div class="row">-->
        <br/>
        <div class="col-xs-12 col-md-12">

          <ul class="list-group">
            <li class="list-group-item list-group-item-success">
              <h4>Tips:</h4>
            </li>
            <li class="list-group-item">
              Simply click on the image to view the PDF!
            </li>
            <li class="list-group-item">
              You can edit the name of your PDF Just by clicking the name!
            </li>
          </ul>
        </div>
      <!--</div>-->



      </div>

    </div>
    <div class="clearfix visible-xs-block"></div>

    <div class="col-xs-12 col-sm-10 col-md-10">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
          <h1>Library</h1>
        </div>

        <div class="row library-row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                  <%= render 'documents/user_library' %>
             </div>
         </div>

        </div>
      </div>


      </div>


    </div>

app/views/users/update.js.erb
$('.user_documents').fadeOut(300);
$('.user_edit').fadeIn(1300);