config/routes.rb
Rails.application.routes.draw do

    root 'welcome#parallax'
    get '/parallax', to: 'welcome#parallax'
    resources :documents
    resources :users

    get '/signin', to: 'sessions#new'
    post '/signin', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'

end

app/views/shared/_edit_user_form.html.erb
<%= form_for @user, :url => user_path, method: :put, :html => { :multipart => true } do |f| %>
    <div class="form-group">
      <h3>Update Info</h3>
    </div>
    <div class="form-group">
      <%= f.text_field :name, placeholder: current_user.name %>
    </div>
    <div class="form-group">
      <%= f.email_field :email, placeholder: current_user.email %>
    </div>
    <div class="form-group">
      <%= f.password_field :password, placeholder: 'Password' %>
    </div>
    <div class="form-group">
      <h4>Update Profile Pic</h4>
      <%= f.file_field :avatar, placeholder: 'Upload Pic'%>
    </div>

    <%= f.submit 'Update',class: 'btn btn-default'%>
    <%= link_to 'Back', user_path(current_user), class: 'back_link btn btn-default' %>
    <br/>
    <%= link_to 'Delete Account', user_path(current_user), method: :delete, data: {confirm:'Are you sure you want to send your account to the fiery pits of Mordor!?'}, class: 'btn btn-danger btn-sm delete-account'  %>
<% end %>

app/views/shared/_login_form.html.erb
<%= form_tag(signin_path, method: :post, class: 'login_form') do %>
    <span id="close-login"><i class="fa fa-times"></i></span>
    <h2>Log-In <br/></h2>
    <div class="form-group">
      <%= email_field_tag :email, nil, placeholder: 'Email', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= password_field_tag :password, nil, placeholder: 'Password', class: 'form-control'  %>
      <br/>
      <%= submit_tag 'Login', class: 'login_link btn btn-default'%>
      <%= link_to 'Sign up!', '#signup', remote: true, class: 'signup_link btn btn-default'%>
    </div>
<% end %>

app/views/shared/_new_document_form.html.erb
  <%= form_for [@user,@document], url: documents_path, html: { multipart: true } do |f| %>
      <div class="form-group">
        <h1>Upload Your PDF!</h1>
      </div>
      <div class="form-group">
        <%= f.text_field :title, class: 'form-control', placeholder: 'Enter a title here...' %>
      </div>
      <div class="form-group">
        <%= link_to 'Upload From URL', '#', class: 'btn btn-default btn-sm upload-by-url' %> <%= link_to 'Upload From Computer', '#', class: 'btn btn-default btn-sm upload-by-computer' %>
      </div>
      <div class="form-group url-upload">
        <%= f.text_field :cover_file_name, class: 'form-control', placeholder: 'Enter a url...' %>
      </div>
      <div class="form-group computer-upload">
        <%= f.file_field :pdf%>
      </div>


      <%= f.submit 'Upload!', class: 'new_doc_submit btn btn-primary', remote: true%>

  <% end %>

app/views/shared/_new_user_form.html.erb
<%= form_for @user, :url => users_path, :html => { :multipart => true } do |f| %>
    <%= flash[:alert] if flash[:alert] %>
    <div class="form-group">
      <%= f.text_field :name, placeholder: 'Name', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.email_field :email, placeholder: 'Email', class: 'form-control'  %>
    </div>
    <div class="form-group">
      <%= f.password_field :password, placeholder: 'Password', class: 'form-control'  %>
    </div>
    <div class="form-group">
      <h4>Upload A Profile Pic(Optional):</h4>
      <%= f.file_field :avatar %>
    </div>
    <%= f.submit class: 'btn btn-default create_user'%>
<% end %>