config/routes.rb
Rails.application.routes.draw do

    root 'welcome#parallax'
    get '/parallax', to: 'welcome#parallax'
    resources :documents
    resources :users

    get '/signin', to: 'sessions#new'
    post '/signin', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VoiceActivated</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'best_in_place.js' %>
  <link href='http://fonts.googleapis.com/css?family=Arvo:700,400italic' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
  <%= init_annyang %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">VoicePDF</a>

    </div>
    <span class="flashes alert navbar-nav">
      <%= flash[:notice] if flash[:notice] %>
      <%= flash[:alert] if flash[:alert] %>
    </span>
    <div>

      <div class="collapse navbar-collapse navbar-links" >
      <ul class="nav navbar-nav navbar-right visible-xs-block" id="myNavBar">
        <% if current_user %>
            <li><%= link_to 'Home', users_path %></li>
            <li><%= link_to 'Library', user_path(current_user)%></li>
            <li><%= link_to 'Sign Out', logout_path, class: 'btn' %></li>
        <% end %>
      </ul>
        <ul class="nav navbar-nav navbar-right hidden-xs" >
          <% if current_user %>
              <li><%= link_to 'Home', users_path %></li>
              <li><%= link_to 'Library', user_path(current_user)%></li>
              <li><%= link_to 'Sign Out', logout_path, class: 'btn' %></li>
          <% end %>
        </ul>

    </div>

    </div>
  </div>
</nav>





<%= yield %>

</body>
</html>